server.port=8881

spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.application.name=together-backstage

spring.datasource.url=jdbc:mysql://175.24.97.72:3306/gameroom
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

